<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="devs" nsURI="http://www.example.org/devs" nsPrefix="devs">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="allDescriptorsAreDefined stateMustHaveOnlyGenericDescriptors"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="allDescriptorsAreDefined" value="&#xA;&#x9;&#x9;&#x9;self.devs.genericstate.genericdescriptor->&#xA;&#x9;&#x9;&#x9;&#x9;forAll(e1:GenericDescriptor | self.descriptor->&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;one(e2:Descriptor | e1.name = e2.name and e1.nature = e2.nature))"/>
      <details key="stateMustHaveOnlyGenericDescriptors" value="&#xA;&#x9;&#x9;&#x9;self.descriptor->&#xA;&#x9;&#x9;&#x9;&#x9;forAll(e1:Descriptor | self.devs.genericstate.genericdescriptor->&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;one(e2:GenericDescriptor | e1.name = e2.name and e1.nature = e2.nature))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="2"
        upperBound="-1" eType="#//Descriptor" containment="true" eOpposite="#//Descriptor/state"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devs" lowerBound="1" eType="#//Devs"
        eOpposite="#//Devs/state"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="typeIsPrimitive typeIsUserDefined sigmaDescriptor phaseDescriptor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="typeIsPrimitive" value="&#xA;&#x9;&#x9;&#x9;self.primitivetype->notEmpty() &#xA;&#x9;&#x9;&#x9;implies self.userdefinedtype->isEmpty()"/>
      <details key="typeIsUserDefined" value="&#xA;&#x9;&#x9;&#x9;self.userdefinedtype->notEmpty() &#xA;&#x9;&#x9;&#x9;implies self.primitivetype->isEmpty()"/>
      <details key="sigmaDescriptor" value="&#xA;&#x9;&#x9;&#x9;self.nature = DescriptorNature::SIGMA &#xA;&#x9;&#x9;&#x9;implies (self.name = 'Sigma' &#xA;&#x9;&#x9;&#x9;and self.primitivetype.oclIsTypeOf(Real))"/>
      <details key="phaseDescriptor" value="&#xA;&#x9;&#x9;&#x9;self.nature = DescriptorNature::PHASE &#xA;&#x9;&#x9;&#x9;implies (self.name = 'Phase' &#xA;&#x9;&#x9;&#x9;and self.primitivetype.oclIsTypeOf(String))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" lowerBound="1"
        eType="#//DescriptorNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitivetype" eType="#//PrimitiveType"
        eOpposite="#//PrimitiveType/genericdescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userdefinedtype" eType="#//UserDefinedType"
        eOpposite="#//UserDefinedType/genericdescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Devs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
        eType="#//State" containment="true" eOpposite="#//State/devs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericstate" lowerBound="1"
        eType="#//GenericState" eOpposite="#//GenericState/devsgeneric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" instanceClassName="java.lang.Object">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericdescriptor" lowerBound="1"
        eType="#//GenericDescriptor" eOpposite="#//GenericDescriptor/primitivetype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericdescriptor" lowerBound="1"
        eType="#//GenericDescriptor" eOpposite="#//GenericDescriptor/userdefinedtype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericState">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="compulsoryPhase compulsorySigma"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="compulsoryPhase" value="&#xA;&#x9;&#x9;&#x9;self.genericdescriptor->&#xA;&#x9;&#x9;&#x9;one(e:GenericDescriptor|e.nature = DescriptorNature::PHASE)"/>
      <details key="compulsorySigma" value="&#xA;&#x9;&#x9;&#x9;self.genericdescriptor->&#xA;&#x9;&#x9;&#x9;one(e:GenericDescriptor|e.nature = DescriptorNature::SIGMA)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devsgeneric" lowerBound="1"
        eType="#//Devs" eOpposite="#//Devs/genericstate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericdescriptor" lowerBound="2"
        upperBound="-1" eType="#//GenericDescriptor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DescriptorNature">
    <eLiterals name="PHASE"/>
    <eLiterals name="SIGMA" value="1"/>
    <eLiterals name="CUSTOM" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptor" eSuperTypes="#//GenericDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="valueMatchType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="valueMatchType" value="&#xA;&#x9;&#x9;&#x9;self.value-> notEmpty() implies &#xA;&#x9;&#x9;&#x9;(self.primitivetype->notEmpty() implies &#xA;&#x9;&#x9;&#x9;&#x9;self.value.content.oclIsTypeOf(self.primitivetype.oclType())&#xA;&#x9;&#x9;&#x9;and  self.userdefinedtype->notEmpty() implies &#xA;&#x9;&#x9;&#x9;&#x9;self.value.content.oclIsTypeOf(self.userdefinedtype.oclType()))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//State"
        eOpposite="#//State/descriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType"/>
  </eClassifiers>
</ecore:EPackage>
