<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="devs" nsURI="http://www.example.org/devs" nsPrefix="devs">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicDevs">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="definitionMustNotHaveValue stateMustHaveValue stateMustMatchDefinition uniqueDefinitionDescriptorNames"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="definitionMustNotHaveValue" value="&#xA;&#x9;&#x9;&#x9;self.definition.descriptor -> &#xA;&#x9;&#x9;&#x9;forAll(d : Descriptor | d.value.content.oclIsUndefined())"/>
      <details key="stateMustHaveValue" value="&#xA;&#x9;&#x9;&#x9;self.state -> &#xA;&#x9;&#x9;&#x9;forAll( s: State | s.descriptor ->&#xA;&#x9;&#x9;&#x9;&#x9;forAll(d: Descriptor | not d.value.content.oclIsUndefined()))"/>
      <details key="stateMustMatchDefinition" value="&#xA;&#x9;&#x9;&#x9;self.definition.descriptor ->&#xA;&#x9;&#x9;&#x9;&#x9;forAll(d1: Descriptor | self.state ->&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;forAll(s: State | s.descriptor ->&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;one(d2: Descriptor | &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;d1.name = d2.name and&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;d1.nature = d2.nature and&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9; d1.type = d2.type)))"/>
      <details key="uniqueDefinitionDescriptorNames" value="&#xA;&#x9;&#x9;&#x9;self.definition.descriptor -> &#xA;&#x9;&#x9;&#x9;&#x9;forAll(d1: Descriptor | self.definition.descriptor ->&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;one(d2: Descriptor | d1.name = d2.name))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputport" lowerBound="1"
        upperBound="-1" eType="#//InputPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputport" lowerBound="1"
        upperBound="-1" eType="#//OutputPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="compulsoryPhase compulsorySigma"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="compulsoryPhase" value="self.descriptor->one(e:Descriptor|e.nature = DescriptorNature::PHASE)"/>
      <details key="compulsorySigma" value="self.descriptor->one(e:Descriptor|e.nature = DescriptorNature::SIGMA)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="2"
        upperBound="-1" eType="#//Descriptor" containment="true" eOpposite="#//Descriptor/state"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atomicDevs" eType="#//AtomicDevs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionIn" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/targetState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionOut" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/sourceState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialState" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="phaseDescriptor sigmaDescriptor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="phaseDescriptor" value="&#xA;&#x9;&#x9;&#x9;self.nature = DescriptorNature::PHASE&#xA;&#x9;&#x9;&#x9;implies (self.name = 'Phase' &#xA;&#x9;&#x9;&#x9;&#x9;and self.type.oclAsType(PrimitiveType).primitive = Primitive::DOUBLE)"/>
      <details key="sigmaDescriptor" value="&#xA;&#x9;&#x9;&#x9;self.nature = DescriptorNature::SIGMA&#xA;&#x9;&#x9;&#x9;implies (self.name = 'Sigma' &#xA;&#x9;&#x9;&#x9;&#x9;and self.type.oclAsType(PrimitiveType).primitive = Primitive::STRING)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//State"
        eOpposite="#//State/descriptor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" lowerBound="1"
        eType="#//DescriptorNature" defaultValueLiteral="CUSTOM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true" eOpposite="#//Type/descriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true" eOpposite="#//Value/descriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
        eType="#//Descriptor" eOpposite="#//Descriptor/type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive" lowerBound="1"
        eType="#//Primitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Primitive">
    <eLiterals name="INTEGER"/>
    <eLiterals name="DOUBLE" value="1"/>
    <eLiterals name="STRING" value="3"/>
    <eLiterals name="BOOLEAN" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toBeDefined" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
        eType="#//Descriptor" eOpposite="#//Descriptor/value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DescriptorNature">
    <eLiterals name="PHASE"/>
    <eLiterals name="SIGMA" value="1"/>
    <eLiterals name="CUSTOM" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" lowerBound="1"
        eType="#//State" eOpposite="#//State/transitionIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceState" lowerBound="1"
        eType="#//State" eOpposite="#//State/transitionOut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Output" eOpposite="#//Output/internaltransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//Input"
        eOpposite="#//Input/externaltransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Input" eOpposite="#//Input/inputport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Output" eOpposite="#//Output/outputport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="externaltransition" lowerBound="1"
        eType="#//ExternalTransition" eOpposite="#//ExternalTransition/input"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputport" lowerBound="1"
        eType="#//InputPort" eOpposite="#//InputPort/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internaltransition" lowerBound="1"
        eType="#//InternalTransition" eOpposite="#//InternalTransition/output"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputport" lowerBound="1"
        eType="#//OutputPort" eOpposite="#//OutputPort/output"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
</ecore:EPackage>
